name: Integration

on:
        workflow_call:
                inputs:
                        environment_name:
                                required: false
                                type: string

jobs:
        report-results:
                permissions: write-all
                runs-on: ubuntu-latest
                name: example
                steps:
                        - name: Checkout
                          uses: actions/checkout/@v3

                        - name: Comment PR
                          uses: thollander/actions-comment-pull-request@v1
                          with:
                                message: |
                                        Hello World
                                GITHUB_TOKEN: ${{ secrets.TEST }}
