name: Integration

on:
        workflow_call:
                inputs:
                        environment_name:
                                required: false
                                type: string

jobs:
        report-results:
                permissions: 
                        pull-requests: write
                runs-on: ubuntu-latest
                name: example
                steps:
                        - name: Checkout
                          uses: actions/checkout/@v3

                        - name: Check python
                          id: check_python
                          run: python --version


                        - name: Install Pipenv
                          id: install_pipenv
                          run: pip install pipenv

                        - name: Install Dependencies
                          id: install_dependencies
                          run: pipenv install

                        - name: Run PyLint
                          id: pylint
                          run: pipenv run pylint app.py | grep "Your code" | tail n -1 >> $$PYLINT_RES


                        - name: Comment PR
                          uses: thollander/actions-comment-pull-request@v1
                          with:
                                message: |
                                        ${{ env.PYLINT_RES }}
                                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
