name: Integration

on:
        workflow_call:
                inputs:
                        environment_name:
                                required: false
                                type: string

jobs:
        report-results:
                permissions: 
                        pull-requests: write
                runs-on: ubuntu-latest
                name: examples
                steps:
                        - name: Checkout
                          uses: actions/checkout/@v3

                        - name: Comment PR
                          uses: thollander/actions-comment-pull-request@v1
                          with:
                                message: |
                                        Hello World
                                GITHUB_TOKEN: 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
