name: Integration

on:
        workflow_call:
                inputs:
                        environment_name:
                                required: false
                                type: string

jobs:
        report-results:
                runs-on: ubuntu-latest
                env:
                          GITHUB_TOKEN: ${{ secrets.TEST }}
                permissions:
                        pull-requests: write
                        issues: read
                steps:
                        - name: report_results
                          id: report_results
                          uses: mschick/add-pr-comment@v2
                          with:
                                  message: |
                                          ** Hello World **
